name: ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
      
      - name: Install Depe
        run: npm install

      - name: Build Docker Images
        run: docker build -t typescript .

      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name my-container typescript